### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by bnaecker** [baccuslab/pyret#23]
Write a file describing the standard coding conventions for anyone wishing to contribute. How are docstrings formatted? In what order are arguments passed and returned?

**Comment by nirum** [comment]
I added a `Contributing` section to the README in b709dcabfa6f0d392e53d638df5f7d773d12dca1 that addresses this. I think the standards we should follow are the same as the [numpy/scipy standards](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) and the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guidelines.
