### ISSUE TITLE
estnln potential bug

### ISSUE THREAD

**Issue by pabloj100000** [baccuslab/pyret#34]
in estnln, (line 157) is computing the conditional probability of the linear prediction given a spike. It is not taking into consideration the firing rate. If two (or more) spikes fall in the same bin they will be contributing as a single spike to the conditional distribution. 

as a toy example consider an on/off cell that fires one spike when the stim is on and two (whithin 1ms) when the stim is off. The NL should look u shaped with the slope in the positive side being twice that in the negative side. Current code will make both slopes identical.

**Comment by bnaecker** [comment]
Avoided in new class-based nonlinearity code, see commit 43463d1
