### ISSUE TITLE
demo: load experiment data file missing

### ISSUE THREAD

**Issue by bongsoos** [baccuslab/pyret#42]
sample data file can't be found.
# Load experiment data

data = np.load('../sample_data/sample_expt.npz')
data.keys()

FileNotFoundError: [Errno 2] No such file or directory: '../sample_data/sample_expt.npz'

**Comment by nirum** [comment]
Whoops, I didn't realize those files were not on Github. The problem is they exceed Github's maximum of 100MB per file. I'll figure out another way to link them into the repo (or decrease the file size or something)

**Comment by nirum** [comment]
I'm waiting to get access to Github's [Large File Storage](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) (LFS) to pull in the dataset
