### ISSUE TITLE
remove `binary.py` from pyret?

### ISSUE THREAD

**Issue by nirum** [baccuslab/pyret#45]
The two functions in `binary.py`, `readbin` and `readbinhdr`, are specific to the binary file types used in the Baccus lab. It seems like to make pyret truly lab independent, that we should keep these functions in a separate repository or location.

Thoughts? It isn't hard for those of us that need it to keep `binary.py` somewhere else on our python path.

**Comment by bnaecker** [comment]
This sounds reasonable. The file format for the current recording setup is definitely not going to change, but they will be different going forward. So I think keeping it in its own repo somewhere else on the Baccus lab pages is a good idea.

B
