### ISSUE TITLE
no more underscores

### ISSUE THREAD

**Issue by nirum** [baccuslab/pyret#49]
Typing out all of the underscores in imports (e.g. `import numpy as _np`) is getting to be an inconvenience. [This post](http://shahriar.svbtle.com/underscores-in-python) suggests that underscores (by convention) represent undocumented parts of the API, which doesn't really fit with how we are using them (for importing external libraries). Also, I haven't seen other projects use the `import numpy as _np` convention, they just use `np`, for example.

Therefore: I vote we remove underscores. thoughts?

**Comment by nirum** [comment]
oh I just realized this is related to #47

**Comment by bnaecker** [comment]
That sounds fine to me. Using '__all__' is cleaner.
