### ISSUE TITLE
Add __init__.py to dev branch's new folder structure

### ISSUE THREAD

**Issue by bnaecker** [baccuslab/pyret#59]
@nirum changed the folder structure of the `dev` branch, putting all the source code in `pyret/pyret`. This is fine, but it means that we have to have the top-level folder itself on our `PYTHONPATH`, rather than the folder in which the repo lives. E.g., I have to include `/usr/local/lib/python3.4/site-packages/pyret` on my `PYTHONPATH`, rather than just `/usr/local/lib/python3.4/site-pacakges`. 

We should include an `__init__.py` file inside the top-level directory, which can just do `from pyret import *`. Thoughts?

**Comment by nirum** [comment]
I think everyone should be installing with: `python setup.py install` or even better `python setup.py develop`

rather than manually editing their path :no_entry_sign:

**Comment by bnaecker** [comment]
Ah I didn't see the updated `setup.py`.
