### ISSUE TITLE
adding a module to generate noise and/or other stimuli

### ISSUE THREAD

**Issue by nirum** [baccuslab/pyret#68]
hey team,

Would people be opposed if I added a module that would generate temporal and spatiotemporal pink noise?

I could also see extending this to add other kinds of stimuli (with the possibility of borrowing from or merging with the deep-retina.structured_stimuli module)

thoughts?

**Comment by nirum** [comment]
@lmcintosh @bnaecker

**Comment by lmcintosh** [comment]
I'd be interested! Seems like it would be nice that a python package for
analyzing the retina would have a battery of different stimuli to probe the
retina.


--
Lane McIntosh
www.lanemcintosh.com

**Comment by nirum** [comment]
management has decided this is never going to happen
