### ISSUE TITLE
add v0.5 updates to the changelog

### ISSUE THREAD

**Issue by nirum** [baccuslab/pyret#81]
What's new since the last changelog?

- lots of function renaming (`plotsta` -> `plot_sta`, `getsta` -> `sta`, etc.)
- removed `containers.py`
- new `nonlinearities.py` module with a scikit-learn interface
- better handling of the sign of the decomposition in `decompose`
- moving `rolling_window` to stimulustools and renaming it to `slicestim`
- `binspikes` and `estfr` now have a single return value (no longer return the time array)

anything else?

**Comment by bnaecker** [comment]
Also `stimcov` is renamed `cov`, `upsample_stim` and `downsample_stim` are just `upsample` and `downsample`.

**Comment by bnaecker** [comment]
I'm adding the 0.5 changes, and bumping the version. That sound good?

**Comment by nirum** [comment]
ya!

👍 🍾 🎆
