### ISSUE TITLE
Support for Python 2.7?

### ISSUE THREAD

**Issue by kdesimone** [baccuslab/pyret#83]
I guess its OK to be compliant with 3 only, but you should probably make mention of this somewhere  in the documentation or the repository so that users won't be baffeled when trying to install on Python 2.7.

$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    import pyret
  File "/Users/kevin/pyret/pyret/__init__.py", line 29, in <module>
    from pyret import *
  File "/Users/kevin/pyret/pyret/nonlinearities.py", line 9, in <module>
    from itertools import zip_longest
ImportError: cannot import name zip_longest

**Comment by bnaecker** [comment]
Several of key components of the 'filtertools' module rely heavily on Python 3's better support for lazy evaluation and iteration. There are several other smaller differences that we'd have to account for, but this large one I think means we don't plan to support 2.7 at all. 

But you are correct that the documentation should much more clearly indicate that the package is 3 only. We will make updates to the docstrings and quickstart on ReadTheDocs to make this very clear.

**Comment by kdesimone** [comment]
OK fair enough, although the benefits of widening your net to attract more users might outweigh the performance gains derive from lazy iteration and evaluation that comes with 3+ but not 2.7.

**Comment by bnaecker** [comment]
Yes, we've thought about the issue of the size of the user base. We'all look more carefully into supporting 2.7. Both Niru (the other developer) and I are traveling out of the country now, and will look into it in a few days when we return. Also, please excuse any late or short replies for the same reason.

**Comment by kdesimone** [comment]
As for the JOSS submission, I don't see any problem with building applications with 3+ in mind, but 2.7 compatibility is something to think about.

**Comment by bnaecker** [comment]
Preliminary Python 2.7 support has been added in a branch I just pushed. I've assigned Niru to review the code, and we'll merge it into master when we're convinced of its correctness.

**Comment by nirum** [comment]
Hi Kevin!

Just merged in python 2.7 support.

thanks,
Niru
